repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --check
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: bash -c 'PYTHONPATH=src mypy src'
        language: system
        types: [python]